---
- hosts: localhost
  become: yes
  vars:
    obsidian_version: "1.3.5"
    slack_version: "4.32.127"
    go_version: "1.20.5"

  tasks:
    - name: update and upgrade apt packages
      apt:
        upgrade: yes
        update-cache: yes

    # - name: Get DEB architecture
    #   shell: dpkg --print-architecture
    #   register: lsb_release
    # - name: Print DEB architecture
    #   debug:
    #     msg: "lsb_release.stdout: {{ lsb_release.stdout }}"

    - name: "Get lsb_release"
      shell: lsb_release -cs
      register: lsb_release
    - name: "Print lsb_release"
      debug:
        msg: "{{ lsb_release.stdout }}"

    - name: confirm keyrings dir exists for syncthing
      file:
        path: /usr/share/keyrings
        state: directory
    - name: add syncthing gpg key
      apt_key:
        url: https://syncthing.net/release-key.gpg
        keyring: /usr/share/keyrings/syncthing-archive-keyring.gpg
        state: present
    - name: add stable syncthing channel to sources
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
        state: present

    - name: install gpg key for sublime
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        keyring: /etc/apt/trusted.gpg.d/sublimehq-archive.gpg
        state: present
    - name: add stable sublime channel to sources
      apt_repository:
        repo: "deb https://download.sublimetext.com/ apt/stable/"
        state: present

    - name: install gpg for terraform
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        state: present
    - name: add terraform main channel to sources 
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main"
        state: present
      
    - name: Add keepassxc repo
      apt_repository:
        repo: ppa:phoerious/keepassxc

    - name: Add firefox ppa repo
      apt_repository:
        repo: ppa:mozillateam/ppa

    - name: prioritise apt version of firefox over snap
      become: true
      shell: |
          echo '
          Package: *
          Pin: release o=LP-PPA-mozillateam
          Pin-Priority: 1001

          Package: firefox
          Pin: version 1:1snap1-0ubuntu2
          Pin-Priority: -1
          ' | tee /etc/apt/preferences.d/mozilla-firefox

    - name: Remove firefox snap because its a PITA
      snap:
        name: firefox
        state: absent

    - name: apt update
      become: yes
      apt:
        # update: yes
        update_cache: yes

    - name: Install packages
      apt:
        pkg:
          - gnome-keyring
          - apt-transport-https
          - sublime-text
          - syncthing
          - zsh
          - terraform
          - htop
          - tmux
          - keepassxc
          - npm
          - firefox
          - hugo

    - name: ensure unattended upgrades does not reinsall snap version of firefox
      become: true
      shell: |
        echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox

    - name: update npm
      shell: npm install -g npm

    - name: install nodejs using nodesource
      become: true
      shell: curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash

    - name: install nodejs
      apt:
        pkg: nodejs
    - name: run syncthing 
      shell: syncthing serve --no-browser --logfile=default

    - name: install Obsidian from deb
      apt:
        deb: "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ obsidian_version }}/obsidian_{{ obsidian_version }}_amd64.deb"

    - name: install VS Code from deb
      apt:
        deb: https://az764295.vo.msecnd.net/stable/695af097c7bd098fbf017ce3ac85e09bbc5dda06/code_1.79.2-1686734195_amd64.deb

    - name: install mega.io cloud drive app from deb
      apt:
        deb: https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megasync-xUbuntu_22.04_amd64.deb

    - name: install Chrome from deb
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: install Slack from deb
      apt:
        deb: "https://downloads.slack-edge.com/releases/linux/{{ slack_version }}/prod/x64/slack-desktop-{{ slack_version }}-amd64.deb"

    - name: install docker using role
      include_role:
        name: docker

    - name: install and configure ohmyzsh
      include_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: liam

    - name: Clone powerlevel10k zsh theme repo
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ ansible_user }}/powerlevel10k"
        depth: 1

    - name: add powerlevel10k theme to zsh config
      lineinfile:
        line: "source /home/{{ ansible_user }}/powerlevel10k/powerlevel10k.zsh-theme"
        path: "/home/{{ ansible_user }}/.zshrc"

    - name: ensure zsh is default shell
      become: yes
      shell: chsh -s $(which zsh)
    
    - name: start syncthing
      shell: /usr/bin/syncthing serve --no-browser --logfile=default &

    - name: autostart syncthing on login
      copy:
        dest: /home/{{ ansible_user }}/.config/autostart/syncthing-start.desktop
        content: |
          [Desktop Entry]
          Categories=Network;FileTransfer;P2P
          Comment=Starts the main syncthing process in the background.
          Exec=/usr/bin/syncthing serve --no-browser --logfile=default
          GenericName=File synchronization
          Icon=syncthing
          Keywords=synchronization;daemon;
          Name=Start Syncthing
          Terminal=false
          Type=Application

    - name: download go tar
      get_url:
        url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz "
        dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"

    - name: remove any existing go path
      file:
        path: /usr/local/go
        state: absent

    - name: untar go 
      unarchive:
        src: /tmp/go{{ go_version }}.linux-amd64.tar.gz
        dest: /usr/local

    - name: add go bin path to path
      shell: export PATH=$PATH:/usr/local/go/bin

    - name: add go path to .profile
      lineinfile:
        line: export PATH=$PATH:/usr/local/go/bin
        path: "/home/{{ ansible_user }}/.profile"

    - name: source .profile
      shell: ". /home/{{ ansible_user }}/.profile"

    - name: Install packages with snap
      snap:
        name: 
          - tradingview
